flycheck-package.el
Making it a PR because I'm not sure if we want it.
To me, it's a good idea, because while "Emacs" is obvious and thus always redundant, "Emacs Lisp" is not. A good example would be [auto-compile](http://melpa.org/#/auto-compile), which has a pretty generic name, but is Emacs Lisp specific, so it's right for the summary to specify it's Emacs Lisp, er, specific.
What's your thoughts?
=> Don't warn if "Emacs" in the package summary is followed by "Lisp"

flycheck-package.el
In older versions of emacs `package-desc-summary` was called `package-desc-doc` [[commit](http://git.savannah.gnu.org/cgit/emacs.git/diff/lisp/emacs-lisp/package.el?h=f56be016d5d2d550f98c83a9d4e61468c71738c2)]. Use an alias so flycheck-package works under older versions of emacs.
Tested under emacs 24.3.
=> Fix emacs 24.3 compatibility

flycheck-package.el
The current usage of `(when deps ...)` makes `flycheck-package` skip some checks when the `Package-Requires` section is empty. This is because `(if '() 'foo 'bar)` evaluates to `'bar`.
As an example, without this fix, flycheck-package won't warn about lexical-binding being used if the Package-Requires is simply `()`.
Here's an example of a simple package that reproduces the issue if this fix is not applied. `flycheck-package` doesn't warn about `lexical-binding` being used.
;;; foo.el --- baz -*- lexical-binding: t -*-
;;; Copyright (C) 2016 Omair Majid
;; Author: Omair Majid <omair.majid@mail.com>
;; URL: foo
;; License: Public Domain
;; Keywords: foo
;; Version: 0.1.20160917
;; Package-Requires: ()
;;; Commentary:
;; 
;;; Code:
(provide 'foo)
;;; foo.el ends here
=> Don't skip some checks if no packages are required

flycheck-package.el
If a function's name is the same as the package's name/prefix, it would be marked as an error.  This allows such functions.  I overlooked this when submitting this function before.  D:
=> Accept functions whose name is the package prefix

README.md
The package name is package-lint, so i think the credits section should mention the same name. Probably a copy paste error?
=> readme : correct package name mentioned in credits

README.md, package-lint-test.el, package-lint.el
The idea is that there's no point in calling package-lint when linting is not desired in the first place.
Additionally, expose a predicate that checks if a buffer looks like a package so that automated linting tools like flycheck-package can keep their old behavior.
---
@purcell, can you rebase it onto master when purcell/flycheck-package#2 is merged?
=> Lint always, even in absence of Version and Package-Requires

package-lint.el
`string-join` is include in the list twice.
=> Remove duplicate `string-join`

package-lint.el
This makes it easy to pick out repeated symbols. It also makes it easier to
tell, at a glance, if any symbols are out of place or missing.
=> List one symbol per line and sort alphabetically

package-lint-test.el, package-lint.el
Still seeing a lot of new recipe submissions ignoring this, which requires manually asking the author to fix it, which defeats the whole point of this check.  Maybe this will help.
=> Note that MELPA strictly requires hyphen separators

package-lint-test.el, package-lint.el
Global minor modes should be defined with
`define-globalized-minor-mode`, and must `:require` the corresponding
feature so setting the automatically-created customization variable
behaves properly.
These checks use a new helper, `package-lint–-check-objects-by-regexp`,
which reads Lisp objects out of the buffer and passes them to a
function specific to that form.
Test cases for the new checks have been added, and old test data
updated to avoid triggering the new checks.
This addresses issue #77.
=> Check that global minor modes are defined properly.

package-lint-test.el, package-lint.el
Such names are not idiomatic, and at odds with the default behavior of
e.g. `define-minor-mode`. They are only used when the group name
without “-mode” is already used for non-mode-specific configuration
options, in which case it should be used as the parent group.
This addresses issue #78.
=> Detect customization group names ending in “-mode”.

package-lint-test.el, package-lint.el
Instead, bad paths must have a symbol delimiter (e.g. a quote) or a /
before the first dot, and a word break after the “d”.
Update the existing test cases so they are valid Emacs Lisp, by
making the test path a string.
This addresses issue #67.
=> Do not warn about paths like “/foo/foo.emacs.dat”.

package-lint-flymake.el
Flymake in Emacs 26 is quite nice, this adds package-lint support.
=> Add support for flymake in Emacs 26+

package-lint-test.el, package-lint.el
This PR refactors the "dependency too high" warning code and fixes an issue where this warning would be raised in undesired situations (see #102) for more information.
@purcell I'm making this PR so you can merge it even if you don't like the new feature in #102.
=> Dependency too high bug

package-lint-flymake.el
`flymake-diag-region` and `flymake-make-diagnostic` were added in
Emacs 26.  `package-lint-setup-flymake` errors out if the user tries
to use the functionality provided by this library when using an older
Emacs, but that doesn't prevent warnings when compiling this library,
which happens even on incompatible Emacsen.
Declare the functions to silence the byte-compiler.  An alternative
approach would be to distribute this library as a separate package,
but that seems a bit drastic.
There's a second commit which does unrelated cleanup.
Totally unrelated, I would recommend you move this to the `melpa` organisation, where it can sit next to `package-build`. :wink:
=> Silence Emacs 25's byte-compiler

package-lint-test.el, package-lint.el
`cl-defmethod` can extend generic definitions coming from other packages: they don't have to start with package prefix.
=> Accept usage of cl-defmethod

package-lint.el
The Emacs Lisp Coding Conventions section in the GNU Emacs Lisp
Reference Manual says: "Occasionally, for a command name intended for
users to use, it is more convenient if some words come before the
package's name prefix. For example, it is our convention to have
commands that list objects named as ‘list-something’, e.g., a package
called ‘frob’ could have a command ‘list-frobs’, when its other global
symbols begin with ‘frob-’. Also, constructs that define functions,
variables, etc., work better if they start with ‘defun’ or ‘defvar’,
so put the name prefix later on in the name."
=> Allow define-/defun-/list- before package prefix

package-lint.el
(for #124)
`package-lint--check-globalized-minor-mode` binds a variable to
```elisp
(intern (package-lint--provided-feature))
```
but if the package lacks a footer this will be nil, which ultimately causes an error when the rest of the check runs.
I think this fix fits, but I'll raise an issue as well in case there's more to it than I'm seeing.
=> Check globalized-minor-mode only when package can be parsed

package-lint.el
These two macros were added in https://github.com/emacs-mirror/emacs/commit/be10c00d3d64d53a7f31441d42f6c5b1f75b9916, part of Emacs 26.0.
=> Note if-let*, when-let* added in Emacs 26.0

package-lint.el
The output now reads like many compilers' output:
```
Entering directory '/absolute/path/to/directory'
filename:line:column: error|warning: message
filename:line:column: error|warning: message
...
```
That means Emacs' compilation-mode can make hyperlinks from the errors and lets you easily jump to the location of each error.
=> Output compiler-style errors and warnings in batch mode

package-lint.el
CC: @lassik
Hi!
I add allow `with` prefix rule.
This idea come from this [comment](https://github.com/purcell/package-lint/pull/122#issuecomment-499829385)
=> allow `with` prefix

package-lint-test.el, package-lint.el
Hi!
Proposal that summary should not end with period.
Currently, almost packages' summary doesn't end with period but some packages not.
=> Warn when package summary end with period

.github/workflows/test.yml
I noticed GitHub Actions is not triggered via #157.
Maybe `pull_request` specification is needed.
=> Run CI when recieve pull request

package-lint.el, run-tests.sh
=> Allow control over whether warnings cause batch checking to fail

package-lint.el
I was running into some issues until I discovered the call to `eq`.
=> Use string= to compare filenames

package-lint-test.el, package-lint.el
Suggest Emacs-24.1 instead of Emacs-24 when enable lexical-binding.
Most warnings are recommended in version format with one decimal
place.  In fact, it was introduced somewhere in the development
version of 24.0.x, so specifying 24.1 is more reasonable than
specifying 24.
=> Suggest Emacs-24.1 instead of Emacs-24 when enable lexical-binding

package-lint-test.el, package-lint.el
Alternate formulation of #182. Replaces Also adds an interactive command, `package-lint-describe-symbol-history`, which fixes #181.
=> Tidy up code for handling symbols added/removed in various Emacs versions

package-lint-flymake.el
package-lint-setup-flymake was deleted in https://github.com/purcell/package-lint/commit/bed4e7f58f7984b720140bd4fee81a3e163f55c0
=> Update docs to refer to non-obsolete functions

package-lint-test.el, package-lint.el
Test defface symbol contains a non-standard separator.
If this PR merged, `package-lint` will start test `defface` symbol
contains a non-standard separator.
Please see testfile to find more concrete examples.
As a side-effect, `package-lint` will check below symbols that matches
below regexp
```elisp
(list (purecopy "Types")
(purecopy (concat "^\\s-*("
(eval-when-compile
(regexp-opt
'(;; Elisp
"defgroup" "deftheme"
"define-widget" "define-error"
"defface" "cl-deftype" "cl-defstruct"
;; CL
"deftype" "defstruct"
"define-condition" "defpackage"
;; CLOS and EIEIO
"defclass")
t))
"\\s-+'?\\(" lisp-mode-symbol-regexp "\\)"))
2)
```
https://github.com/emacs-mirror/emacs/blob/47f2a39f427f2e7bfd3de371316e3a2c47841340/lisp/emacs-lisp/lisp-mode.el#L139-L154
=> Test defface symbol contains a non-standard separator

package-lint.el
It's like `ob-` and `ox-`, just slightly newer, I think.
=> Add "ol-" entry to package-lint--allowed-prefix-mappings

package-lint.el
define-advice will define symbols that start with the name of the
function being advised, so they should be exempt from the package
prefix check.
=> Consider define-advice forms to be global definitions

package-lint.el
```
In package-lint--region-empty-p:
lib/package-lint/package-lint.el:1062:14: Warning:
‘inhibit-changing-match-data’ is an obsolete variable (as of 29.1); use
‘save-match-data’ instead.
```
=> Use save-match-data instead of obsolete inhibit-changing-match-data

package-lint.el
Fix long docstrings for Emacs 28. There is also the advantage that shorter
docstrings are display more nicely by my Marginalia annotation package.
I just saw this warnings pop up when I updated the package. Thank for this package and your work on MELPA! Think it gives a great boost to package quality across the ecosystem.
=> Linting the linter

package-lint-test.el, package-lint.el
According to the manual, an entry in Package-Requires header may lack a version string.
An entry without a version is considered to have version "0".
https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html
So we should accept it.
=> Accept Package-Requires header without version

package-lint.el
The byte-compiler recently got more fussy about quotes.
=> Replace certain single quotes in docstrings

package-lint.el
=> Handle bindings from define-obsolete-*-alias returned by imenu in latest Emacsen

package-lint.el
Use-package requires using these prefixes to define new keywords.
Following up on discussion in #125.
=> Add use-package keyword definition prefixes to sane prefixes

.github/workflows/test.yml, package-lint-test.el, package-lint.el, run-tests.sh
=> Add support for functions provided by the compat package

package-lint.el
Hi, I would like to propose you adding `org-babel-expand-body:` for org-babel as the same as `org-babel-execute`.
Cheers.
=> Add org-babel-expand-body:

package-lint-test.el, package-lint.el
Emacs 30 was released last month, so now the head version is 31.
I've noticed this problem when I tried running package-lint on a package requiring Emacs 30.
=> Bump the emacs-head-version

package-lint.el
I proposed adding support for multi-line `Package-Requires` headers in #282.  The implementation added in #283 was incomplete and resulted in two new compiler warnings.  This pr finishes the implementation and pacifies the compiler.
=> Complete support for multi-line Package-Requires header
